pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: Docker@1
    displayName: Build cdt-infra-base:ubuntu-16.04
    inputs:
      command: build
      dockerFile: docker/cdt-infra-base/ubuntu-16.04/Dockerfile
      useDefaultContext: false
      buildContext: docker/
      imageName: cdt-infra-base:ubuntu-16.04
      addDefaultLabels: false
  - task: Docker@1
    displayName: cdt-infra-eclipse-full:ubuntu-16.04
    inputs:
      command: build
      dockerFile: docker/cdt-infra-eclipse-full/ubuntu-16.04/Dockerfile
      useDefaultContext: false
      buildContext: docker/
      imageName: cdt-infra-eclipse-full:ubuntu-16.04
      addDefaultLabels: false
  - task: Docker@1
    displayName: Build cdt-infra-platform-sdk:sdk4.9-ubuntu-16.04
    inputs:
      command: build
      dockerFile: docker/cdt-infra-platform-sdk/sdk4.9-ubuntu-16.04/Dockerfile
      useDefaultContext: false
      buildContext: docker/
      imageName: cdt-infra-platform-sdk:sdk4.9-ubuntu-16.04
      addDefaultLabels: false