apiVersion: v1
kind: Pod
spec:
  containers:
  - name: cdt
    image: quay.io/kummallinen/cdt-infra-eclipse-full:v0.2-ubuntu-16.04@sha256:1803f980db3877de84fda6f9ef77019573862308f2c0ba470e02d3f492a22c18
    tty: true
    command: ["/bin/sh"]
    args: ["-c", "/home/cdt/.vnc/xstartup.sh && cat"]
    resources:
      requests:
        memory: "2.6Gi"
        cpu: "1.3"
      limits:
        memory: "2.6Gi"
        cpu: "1.3"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    configMap: 
      name: m2-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}