apiVersion: v1
kind: Pod
spec:
  containers:
  - name: platform-sdk
    image: quay.io/jonahgraham/cdt-infra-platform-sdk:ubuntu-16.04@sha256:9049ac0439646630062c240c640f6d46ed132fc67dd25389ab06935729039e02
    tty: true
    args: ["cat"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    configMap: 
      name: m2-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}