apiVersion: v1
kind: Pod
spec:
  containers:
  - name: platform-sdk
    image: quay.io/eclipse-cdt/cdt-infra-platform-sdk@sha256:664154af0b9b972c91009f1aa5597f2c7d4ea6589a93ef38a6bb2d6c21df73b0
    tty: true
    command: ["/bin/sh"]
    args: ["-c", "cat"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
