apiVersion: v1
kind: Pod
spec:
  containers:
  - name: platform-sdk
    image: quay.io/eclipse-cdt/cdt-infra-platform-sdk@sha256:f2e6e6d9ed3d65bca178a16ab0a40b92c02a2222983cd7e03294c36f2cd764e2
    tty: true
    args: ["/home/vnc/.vnc/xstartup.sh", "cat"]
    resources:
      requests:
        memory: "2.6Gi"
        cpu: "1"
      limits:
        memory: "2.6Gi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
