apiVersion: v1
kind: Pod
spec:
  containers:
  - name: platform-sdk
    image: quay.io/eclipse-cdt/cdt-infra-platform-sdk@sha256:1a0ab5468640aa6c346f495bde32ebf2d8df3728810b14f44802372b4df41f68
    tty: true
    command: ["/bin/sh"]
    args: ["-c", "cat"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
