apiVersion: v1
kind: Pod
spec:
  containers:
  - name: platform-sdk
    image: quay.io/kummallinen/cdt-infra-platform-sdk:stable-sdk4.9-ubuntu-16.04@sha256:c71dda47b443eebab1cc8cf083a9abb721006f5d3b349ab6ded3cac4d594f321
    tty: true
    args: ["cat"]
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
  volumes:
  - name: settings-xml
    configMap: 
      name: m2-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}